// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type Gender string

const (
	GenderMALE   Gender = "MALE"
	GenderFEMALE Gender = "FEMALE"
	GenderOTHER  Gender = "OTHER"
)

func (e *Gender) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Gender(s)
	case string:
		*e = Gender(s)
	default:
		return fmt.Errorf("unsupported scan type for Gender: %T", src)
	}
	return nil
}

type NullGender struct {
	Gender Gender `json:"gender"`
	Valid  bool   `json:"valid"` // Valid is true if Gender is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGender) Scan(value interface{}) error {
	if value == nil {
		ns.Gender, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Gender.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGender) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Gender), nil
}

type Account struct {
	ID           int64              `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Profile struct {
	ID            int64              `json:"id"`
	AccountID     int64              `json:"account_id"`
	State         string             `json:"state"`
	Occupation    string             `json:"occupation"`
	MonthlyIncome int64              `json:"monthly_income"`
	Age           int32              `json:"age"`
	Gender        Gender             `json:"gender"`
	ChildrenCount int32              `json:"children_count"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type RefreshToken struct {
	ID        int64              `json:"id"`
	AccountID int64              `json:"account_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Scheme struct {
	ID             int64              `json:"id"`
	Name           string             `json:"name"`
	Description    string             `json:"description"`
	State          string             `json:"state"`
	SourceUrl      string             `json:"source_url"`
	LastVerifiedAt pgtype.Timestamptz `json:"last_verified_at"`
}

type SchemeRule struct {
	ID       int64       `json:"id"`
	SchemeID pgtype.Int8 `json:"scheme_id"`
	Field    string      `json:"field"`
	Operator string      `json:"operator"`
	Value    []byte      `json:"value"`
}
