// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type Gender string

const (
	GenderMale         Gender = "male"
	GenderFemale       Gender = "female"
	GenderOther        Gender = "other"
	GenderNotSpecified Gender = "not_specified"
)

func (e *Gender) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Gender(s)
	case string:
		*e = Gender(s)
	default:
		return fmt.Errorf("unsupported scan type for Gender: %T", src)
	}
	return nil
}

type NullGender struct {
	Gender Gender `json:"gender"`
	Valid  bool   `json:"valid"` // Valid is true if Gender is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGender) Scan(value interface{}) error {
	if value == nil {
		ns.Gender, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Gender.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGender) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Gender), nil
}

type Account struct {
	ID           int64              `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Profile struct {
	ID                  int64              `json:"id"`
	AccountID           int64              `json:"account_id"`
	State               pgtype.Text        `json:"state"`
	Occupation          string             `json:"occupation"`
	MonthlyIncome       pgtype.Int8        `json:"monthly_income"`
	Age                 pgtype.Int4        `json:"age"`
	Gender              NullGender         `json:"gender"`
	ChildrenCount       pgtype.Int4        `json:"children_count"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	District            pgtype.Text        `json:"district"`
	IncomeCurrency      string             `json:"income_currency"`
	FamilySize          pgtype.Int4        `json:"family_size"`
	ChildrenSchoolGoing pgtype.Bool        `json:"children_school_going"`
	IsRegisteredWorker  pgtype.Bool        `json:"is_registered_worker"`
	CasteCategory       pgtype.Text        `json:"caste_category"`
	HasBankAccount      pgtype.Bool        `json:"has_bank_account"`
	DocumentsAvailable  []string           `json:"documents_available"`
	Language            string             `json:"language"`
	Name                string             `json:"name"`
}

type RefreshToken struct {
	ID        int64              `json:"id"`
	AccountID int64              `json:"account_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Scheme struct {
	ID             int64              `json:"id"`
	Name           string             `json:"name"`
	Description    string             `json:"description"`
	State          string             `json:"state"`
	SourceUrl      string             `json:"source_url"`
	LastVerifiedAt pgtype.Timestamptz `json:"last_verified_at"`
	DepartmentName pgtype.Text        `json:"department_name"`
}

type SchemeRule struct {
	ID       int64       `json:"id"`
	SchemeID pgtype.Int8 `json:"scheme_id"`
	Field    string      `json:"field"`
	Operator string      `json:"operator"`
	Value    []byte      `json:"value"`
}
