// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: profile.sql

package sqlc

import (
	"context"
)

const createProfile = `-- name: CreateProfile :one
INSERT INTO profiles (
    state,
    occupation,
    monthly_income,
    age,
    gender,
    children_count
)
VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING
    id,
    state,
    occupation,
    monthly_income,
    age,
    gender,
    children_count
`

type CreateProfileParams struct {
	State         string `json:"state"`
	Occupation    string `json:"occupation"`
	MonthlyIncome int64  `json:"monthly_income"`
	Age           int32  `json:"age"`
	Gender        Gender `json:"gender"`
	ChildrenCount int32  `json:"children_count"`
}

type CreateProfileRow struct {
	ID            int64  `json:"id"`
	State         string `json:"state"`
	Occupation    string `json:"occupation"`
	MonthlyIncome int64  `json:"monthly_income"`
	Age           int32  `json:"age"`
	Gender        Gender `json:"gender"`
	ChildrenCount int32  `json:"children_count"`
}

func (q *Queries) CreateProfile(ctx context.Context, arg CreateProfileParams) (CreateProfileRow, error) {
	row := q.db.QueryRow(ctx, createProfile,
		arg.State,
		arg.Occupation,
		arg.MonthlyIncome,
		arg.Age,
		arg.Gender,
		arg.ChildrenCount,
	)
	var i CreateProfileRow
	err := row.Scan(
		&i.ID,
		&i.State,
		&i.Occupation,
		&i.MonthlyIncome,
		&i.Age,
		&i.Gender,
		&i.ChildrenCount,
	)
	return i, err
}
