// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: profile.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProfile = `-- name: CreateProfile :one
INSERT INTO profiles (
    name,
    account_id,
    state,
    district,
    occupation,
    monthly_income,
    income_currency,
    family_size,
    children_count,
    children_school_going,
    age,
    gender,
    is_registered_worker,
    caste_category,
    has_bank_account,
    documents_available,
    language
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8,
    $9, $10, $11, $12, $13, $14, $15, $16, $17
)
RETURNING id, account_id, state, occupation, monthly_income, age, gender, children_count, created_at, district, income_currency, family_size, children_school_going, is_registered_worker, caste_category, has_bank_account, documents_available, language, name
`

type CreateProfileParams struct {
	Name                string      `json:"name"`
	AccountID           int64       `json:"account_id"`
	State               pgtype.Text `json:"state"`
	District            pgtype.Text `json:"district"`
	Occupation          string      `json:"occupation"`
	MonthlyIncome       pgtype.Int8 `json:"monthly_income"`
	IncomeCurrency      string      `json:"income_currency"`
	FamilySize          pgtype.Int4 `json:"family_size"`
	ChildrenCount       pgtype.Int4 `json:"children_count"`
	ChildrenSchoolGoing pgtype.Bool `json:"children_school_going"`
	Age                 pgtype.Int4 `json:"age"`
	Gender              NullGender  `json:"gender"`
	IsRegisteredWorker  pgtype.Bool `json:"is_registered_worker"`
	CasteCategory       pgtype.Text `json:"caste_category"`
	HasBankAccount      pgtype.Bool `json:"has_bank_account"`
	DocumentsAvailable  []string    `json:"documents_available"`
	Language            string      `json:"language"`
}

func (q *Queries) CreateProfile(ctx context.Context, arg CreateProfileParams) (Profile, error) {
	row := q.db.QueryRow(ctx, createProfile,
		arg.Name,
		arg.AccountID,
		arg.State,
		arg.District,
		arg.Occupation,
		arg.MonthlyIncome,
		arg.IncomeCurrency,
		arg.FamilySize,
		arg.ChildrenCount,
		arg.ChildrenSchoolGoing,
		arg.Age,
		arg.Gender,
		arg.IsRegisteredWorker,
		arg.CasteCategory,
		arg.HasBankAccount,
		arg.DocumentsAvailable,
		arg.Language,
	)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.State,
		&i.Occupation,
		&i.MonthlyIncome,
		&i.Age,
		&i.Gender,
		&i.ChildrenCount,
		&i.CreatedAt,
		&i.District,
		&i.IncomeCurrency,
		&i.FamilySize,
		&i.ChildrenSchoolGoing,
		&i.IsRegisteredWorker,
		&i.CasteCategory,
		&i.HasBankAccount,
		&i.DocumentsAvailable,
		&i.Language,
		&i.Name,
	)
	return i, err
}

const getProfileByAccountID = `-- name: GetProfileByAccountID :one
SELECT id, account_id, state, occupation, monthly_income, age, gender, children_count, created_at, district, income_currency, family_size, children_school_going, is_registered_worker, caste_category, has_bank_account, documents_available, language, name
FROM profiles
WHERE account_id = $1
`

func (q *Queries) GetProfileByAccountID(ctx context.Context, accountID int64) (Profile, error) {
	row := q.db.QueryRow(ctx, getProfileByAccountID, accountID)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.State,
		&i.Occupation,
		&i.MonthlyIncome,
		&i.Age,
		&i.Gender,
		&i.ChildrenCount,
		&i.CreatedAt,
		&i.District,
		&i.IncomeCurrency,
		&i.FamilySize,
		&i.ChildrenSchoolGoing,
		&i.IsRegisteredWorker,
		&i.CasteCategory,
		&i.HasBankAccount,
		&i.DocumentsAvailable,
		&i.Language,
		&i.Name,
	)
	return i, err
}

const getProfileByID = `-- name: GetProfileByID :one
SELECT id, account_id, state, occupation, monthly_income, age, gender, children_count, created_at, district, income_currency, family_size, children_school_going, is_registered_worker, caste_category, has_bank_account, documents_available, language, name
FROM profiles
WHERE id = $1
`

func (q *Queries) GetProfileByID(ctx context.Context, id int64) (Profile, error) {
	row := q.db.QueryRow(ctx, getProfileByID, id)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.State,
		&i.Occupation,
		&i.MonthlyIncome,
		&i.Age,
		&i.Gender,
		&i.ChildrenCount,
		&i.CreatedAt,
		&i.District,
		&i.IncomeCurrency,
		&i.FamilySize,
		&i.ChildrenSchoolGoing,
		&i.IsRegisteredWorker,
		&i.CasteCategory,
		&i.HasBankAccount,
		&i.DocumentsAvailable,
		&i.Language,
		&i.Name,
	)
	return i, err
}

const updateProfile = `-- name: UpdateProfile :one
UPDATE profiles
SET
    name = $2,
    state = $3,
    district = $4,
    occupation = $5,
    monthly_income = $6,
    income_currency = $7,
    family_size = $8,
    children_count = $9,
    children_school_going = $10,
    age = $11,
    gender = $12,
    is_registered_worker = $13,
    caste_category = $14,
    has_bank_account = $15,
    documents_available = $16,
    language = $17
WHERE account_id = $1
RETURNING id, account_id, state, occupation, monthly_income, age, gender, children_count, created_at, district, income_currency, family_size, children_school_going, is_registered_worker, caste_category, has_bank_account, documents_available, language, name
`

type UpdateProfileParams struct {
	AccountID           int64       `json:"account_id"`
	Name                string      `json:"name"`
	State               pgtype.Text `json:"state"`
	District            pgtype.Text `json:"district"`
	Occupation          string      `json:"occupation"`
	MonthlyIncome       pgtype.Int8 `json:"monthly_income"`
	IncomeCurrency      string      `json:"income_currency"`
	FamilySize          pgtype.Int4 `json:"family_size"`
	ChildrenCount       pgtype.Int4 `json:"children_count"`
	ChildrenSchoolGoing pgtype.Bool `json:"children_school_going"`
	Age                 pgtype.Int4 `json:"age"`
	Gender              NullGender  `json:"gender"`
	IsRegisteredWorker  pgtype.Bool `json:"is_registered_worker"`
	CasteCategory       pgtype.Text `json:"caste_category"`
	HasBankAccount      pgtype.Bool `json:"has_bank_account"`
	DocumentsAvailable  []string    `json:"documents_available"`
	Language            string      `json:"language"`
}

func (q *Queries) UpdateProfile(ctx context.Context, arg UpdateProfileParams) (Profile, error) {
	row := q.db.QueryRow(ctx, updateProfile,
		arg.AccountID,
		arg.Name,
		arg.State,
		arg.District,
		arg.Occupation,
		arg.MonthlyIncome,
		arg.IncomeCurrency,
		arg.FamilySize,
		arg.ChildrenCount,
		arg.ChildrenSchoolGoing,
		arg.Age,
		arg.Gender,
		arg.IsRegisteredWorker,
		arg.CasteCategory,
		arg.HasBankAccount,
		arg.DocumentsAvailable,
		arg.Language,
	)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.State,
		&i.Occupation,
		&i.MonthlyIncome,
		&i.Age,
		&i.Gender,
		&i.ChildrenCount,
		&i.CreatedAt,
		&i.District,
		&i.IncomeCurrency,
		&i.FamilySize,
		&i.ChildrenSchoolGoing,
		&i.IsRegisteredWorker,
		&i.CasteCategory,
		&i.HasBankAccount,
		&i.DocumentsAvailable,
		&i.Language,
		&i.Name,
	)
	return i, err
}
