// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scheme_rules.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSchemeRule = `-- name: CreateSchemeRule :one
INSERT INTO scheme_rules (
    scheme_id,
    field,
    operator,
    value
)
VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING
    id,
    scheme_id,
    field,
    operator,
    value
`

type CreateSchemeRuleParams struct {
	SchemeID pgtype.Int8 `json:"scheme_id"`
	Field    string      `json:"field"`
	Operator string      `json:"operator"`
	Value    []byte      `json:"value"`
}

func (q *Queries) CreateSchemeRule(ctx context.Context, arg CreateSchemeRuleParams) (SchemeRule, error) {
	row := q.db.QueryRow(ctx, createSchemeRule,
		arg.SchemeID,
		arg.Field,
		arg.Operator,
		arg.Value,
	)
	var i SchemeRule
	err := row.Scan(
		&i.ID,
		&i.SchemeID,
		&i.Field,
		&i.Operator,
		&i.Value,
	)
	return i, err
}

const deleteSchemeRule = `-- name: DeleteSchemeRule :one
DELETE FROM scheme_rules
WHERE id = $1
RETURNING id
`

func (q *Queries) DeleteSchemeRule(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, deleteSchemeRule, id)
	var id_2 int64
	err := row.Scan(&id_2)
	return id_2, err
}

const getSchemeRuleByID = `-- name: GetSchemeRuleByID :one
SELECT
    id,
    scheme_id,
    field,
    operator,
    value
FROM scheme_rules
WHERE id = $1
`

func (q *Queries) GetSchemeRuleByID(ctx context.Context, id int64) (SchemeRule, error) {
	row := q.db.QueryRow(ctx, getSchemeRuleByID, id)
	var i SchemeRule
	err := row.Scan(
		&i.ID,
		&i.SchemeID,
		&i.Field,
		&i.Operator,
		&i.Value,
	)
	return i, err
}

const getSchemeRulesBySchemeID = `-- name: GetSchemeRulesBySchemeID :many
SELECT
    id,
    scheme_id,
    field,
    operator,
    value
FROM scheme_rules
WHERE scheme_id = $1
ORDER BY id
`

func (q *Queries) GetSchemeRulesBySchemeID(ctx context.Context, schemeID pgtype.Int8) ([]SchemeRule, error) {
	rows, err := q.db.Query(ctx, getSchemeRulesBySchemeID, schemeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SchemeRule
	for rows.Next() {
		var i SchemeRule
		if err := rows.Scan(
			&i.ID,
			&i.SchemeID,
			&i.Field,
			&i.Operator,
			&i.Value,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
