// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: schemes.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createScheme = `-- name: CreateScheme :one
INSERT INTO schemes (
    name,
    description,
    state,
    source_url,
    last_verified_at
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING
    id,
    name,
    description,
    state,
    source_url,
    last_verified_at
`

type CreateSchemeParams struct {
	Name           string             `json:"name"`
	Description    string             `json:"description"`
	State          string             `json:"state"`
	SourceUrl      string             `json:"source_url"`
	LastVerifiedAt pgtype.Timestamptz `json:"last_verified_at"`
}

func (q *Queries) CreateScheme(ctx context.Context, arg CreateSchemeParams) (Scheme, error) {
	row := q.db.QueryRow(ctx, createScheme,
		arg.Name,
		arg.Description,
		arg.State,
		arg.SourceUrl,
		arg.LastVerifiedAt,
	)
	var i Scheme
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.State,
		&i.SourceUrl,
		&i.LastVerifiedAt,
	)
	return i, err
}

const deleteScheme = `-- name: DeleteScheme :one
DELETE FROM schemes
WHERE id = $1
RETURNING id
`

func (q *Queries) DeleteScheme(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, deleteScheme, id)
	var id_2 int64
	err := row.Scan(&id_2)
	return id_2, err
}

const getSchemeByID = `-- name: GetSchemeByID :one
SELECT
    id,
    name,
    description,
    state,
    source_url,
    last_verified_at
FROM schemes
WHERE id = $1
`

func (q *Queries) GetSchemeByID(ctx context.Context, id int64) (Scheme, error) {
	row := q.db.QueryRow(ctx, getSchemeByID, id)
	var i Scheme
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.State,
		&i.SourceUrl,
		&i.LastVerifiedAt,
	)
	return i, err
}

const listSchemes = `-- name: ListSchemes :many
SELECT
    id,
    name,
    description,
    state,
    source_url,
    last_verified_at
FROM schemes
ORDER BY id
`

func (q *Queries) ListSchemes(ctx context.Context) ([]Scheme, error) {
	rows, err := q.db.Query(ctx, listSchemes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Scheme
	for rows.Next() {
		var i Scheme
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.State,
			&i.SourceUrl,
			&i.LastVerifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSchemesByState = `-- name: ListSchemesByState :many
SELECT
    id,
    name,
    description,
    state,
    source_url,
    last_verified_at
FROM schemes
WHERE state = $1
ORDER BY id
`

func (q *Queries) ListSchemesByState(ctx context.Context, state string) ([]Scheme, error) {
	rows, err := q.db.Query(ctx, listSchemesByState, state)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Scheme
	for rows.Next() {
		var i Scheme
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.State,
			&i.SourceUrl,
			&i.LastVerifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateScheme = `-- name: UpdateScheme :one
UPDATE schemes
SET
    name = $2,
    description = $3,
    state = $4,
    source_url = $5,
    last_verified_at = $6
WHERE id = $1
RETURNING
    id,
    name,
    description,
    state,
    source_url,
    last_verified_at
`

type UpdateSchemeParams struct {
	ID             int64              `json:"id"`
	Name           string             `json:"name"`
	Description    string             `json:"description"`
	State          string             `json:"state"`
	SourceUrl      string             `json:"source_url"`
	LastVerifiedAt pgtype.Timestamptz `json:"last_verified_at"`
}

func (q *Queries) UpdateScheme(ctx context.Context, arg UpdateSchemeParams) (Scheme, error) {
	row := q.db.QueryRow(ctx, updateScheme,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.State,
		arg.SourceUrl,
		arg.LastVerifiedAt,
	)
	var i Scheme
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.State,
		&i.SourceUrl,
		&i.LastVerifiedAt,
	)
	return i, err
}
